apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
  ownerReferences:
  - apiVersion: stable.example.com/v1
    blockOwnerDeletion: false
    controller: false
    kind: CrontTab
    name: my-new-cron-object
    uid: 2692d619-36e3-11e9-ba94-08002748523c